//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDienThoaiEntity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACCOUNT
    {
        public string ID_ACCOUNT { get; set; }

        [Display(Name = "Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Chưa nhập email !")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }
        public string TYPE_ACCOUNT { get; set; }

        public string ID_CUSTOMER { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Chưa nhập mật khẩu")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Mật khẩu phải có ít nhất 6 ký tự")]
        public string PASSWORD { get; set; }

        [Display(Name = "Xác nhận mật khẩu")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Chưa nhập mật khẩu")]
        [DataType(DataType.Password)]
        [Compare("PASSWORD", ErrorMessage = "Mật khẩu xác nhận không chính xác")]
        public string CONFIRMPASSWORD { get; set; }

        public Nullable<bool> ISEMAILVERIFY { get; set; }

        public Nullable<System.Guid> ACTIVATIONCODE { get; set; }

        public string RESETPASSWORDCODE { get; set; }

        [Display(Name = "Lưu mật khẩu")]
        public bool RememberMe { get; set; }


        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
