//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDienThoaiEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL
    {
        public int ID { get; set; }
        public string ID_SIM { get; set; }
        public Nullable<System.DateTime> TIME_START { get; set; }
        public Nullable<System.DateTime> TIME_STOP { get; set; }
        public Nullable<int> MINUTE_AFTER7 { get; set; }
        public Nullable<int> MINUTE_AFTER23 { get; set; }
        public Nullable<int> FARE { get; set; }
    
        public virtual SIM SIM { get; set; }
    }
}
