//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDienThoaiEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARE
    {
        public string ID_FARE { get; set; }
        public Nullable<System.TimeSpan> TIME_START { get; set; }
        public Nullable<System.TimeSpan> TIME_STOP { get; set; }
        public Nullable<int> FARE1 { get; set; }
    }
}
